### ISSUE TITLE
When execute ./ob_tester.py --debug the command then get this error 

### ISSUE THREAD

**Issue by DavidSunGoldhub** [firepol/ccxt-websockets-db-updater#7]
Traceback (most recent call last):
  File "./ob_tester.py", line 8, in <module>
    import ob_updater
  File "/home/davidsun/ccxt-websockets-db-updater/ob_updater.py", line 13, in <module>
    import book_utils
  File "/home/davidsun/ccxt-websockets-db-updater/book_utils.py", line 6, in <module>
    import utils
  File "/home/davidsun/ccxt-websockets-db-updater/utils.py", line 5, in <module>
    import ccxt.async_support as ccxt
  File "/home/davidsun/ccxt-websockets-db-updater/env/lib/python3.6/site-packages/ccxt/__init__.py", line 183, in <module>
    from ccxt.poloniex import poloniex                          # noqa: F401
  File "/home/davidsun/ccxt-websockets-db-updater/env/lib/python3.6/site-packages/ccxt/poloniex.py", line 1273
    else:
       ^
IndentationError: expected an indented block

**Comment by firepol** [comment]
Hi, sorry for the late reply, the error indicates issues with the imported ccxt. I updated it a few days ago, so you can try to update it first by removing `ccxt`, then by reinstalling the dependencies in the `requirements.txt` (you can see it as a custom version I created from lfern's repository) as follows:

```
pip uninstall ccxt
pip install -r requirements.txt
```

I tested this a few days ago and I had similar errors, which now are gone after my latest update of the ccxt dependency. Cheers.
